set-option -sa terminal-overrides ",$TERM:RGB"
set-option -g default-terminal "tmux-256color"
set-option -sg escape-time 300

run-shell 'tmux setenv -g TMUX_VERSION $(tmux -V | sed -En "s/^tmux[^0-9]*([.0-9]+).*/\1/p")'
if-shell '[ "$(echo "$TMUX_VERSION >= 1.9" | bc)" -eq 1 ]' {
    set-option -g focus-events on
}

setw -g mode-keys vi
